baseURL = "https://bigelectrons.com/" # Should be without the www. otherwise issues with CORS might happen
languageCode = "en-us"
title = "bigelectrons"
name = "Joesan"

disableKinds = "true"

[params]
mainSections = ["post"]

