name: Build and Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'util/**'
      - 'help/**'
      - '.gitignore'
      - 'LICENSE'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check HTTP Links
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: -v "content/**/*.md"
      # This action below creates an issue automatically
      #- name: Create Issue From File
       # uses: peter-evans/create-issue-from-file@v2
        #with:
         # title: Link Checker Report
          #content-filepath: ./lychee/out.md
          #labels: report, automated issue

  listDraftContent:
    needs: linkChecker
    #runs-on: macos-10.15
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      TARGET_BRANCH: draft-status
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install Scala
        run: |-
          brew install scala
          git config --global user.email "workflow-bot@bigelectrons.com"
          git config --global user.name "workflow-bot"
          git checkout --orphan $TARGET_BRANCH
          bash ./.github/scripts/list_draft_content content draftStatus.txt
          rm README.md
          echo -e "TEMPORARY BRANCH, PLEASE NAVIGATE TO THE MASTER BRANCH" > README.md
          git add .
          git commit -m "generated draftStatus.txt"
          git push --set-upstream origin $TARGET_BRANCH --force


